replicas: 1
interface: wg0
listenPort: 51820
network: 10.10.0.1/24
networkInterface: eth0
image: sosedoff/wireguard:latest
dnsForward: /etc/resolv.conf
dnsPrivateZone: internal
deployKind: DaemonSet
metrics: true
