#!/bin/bash

set -e

log() {
  echo "entrypoint: $1"
}

configure_ip_forwarding() {
  log "enabling ip forwarding"
  sysctl -w net.ipv4.ip_forward=1
  sysctl -w net.ipv4.conf.all.forwarding=1
  sysctl -w net.ipv6.conf.all.forwarding=1
}

configure_coredns() {
  log "creating coredns config"

  mkdir -p /etc/coredns
  cat << END >> /etc/coredns/Corefile
. {
  forward . /etc/resolv.conf
  log
  errors
  cache
}
END
}

if [[ ! -z "$WG_IP_FORWARDING" ]]; then
  configure_ip_forwarding
fi

if [ ! -f "/etc/coredns/Corefile" ]; then
  configure_coredns
fi

exec "$@"
