name: push

on:
  push:
    branches:
      - main

env:
  GO_VERSION: 1.19
  CGO_ENABLED: 0
  DOCKER_REPOSITORY: sosedoff/wireguard

jobs:
  docker-release:
    name: Publish Docker images
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Configure docker build context
        uses: docker/setup-buildx-action@v2

      - name: Set reference tags
        id: refs
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/v}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REPOSITORY }}:$(date -u +"%Y%m%d")
            ${{ env.DOCKER_REPOSITORY }}:latest
          platforms: linux/amd64
